/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorldJNI */

#ifndef _Included_HelloWorldJNI
#define _Included_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorldJNI
 * Method:    matmulti
 * Signature: (I[[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_HelloWorldJNI_matmulti
  (JNIEnv *, jobject, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
